baseURL = 'https://example.org/'
languageCode = 'fr-FR'
title = 'Hot coffee - devBlog ☕'
theme = 'hugo-bearcub'
themeStyle = 'herman'
copyright = "Ivan Béthus (CC BY 4.0)"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[languages]
  [languages.en]
    disabled = false
    contentDir = 'content/en'
    languageCode = 'en-US'
    languageDirection = ""
    languageName = "English"
    weight = 2
  [languages.fr]
    disabled = false
    contentDir = 'content/fr'
    languageCode = 'fr-FR'
    languageDirection = ""
    languageName = "Français"
    weight = 1

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = false

[taxonomies]
  genre = 'genres'
  tag = 'tags'

[params]
  # The description of your website
  description = "Another blog about development."

  # The path to your favicon
  favicon = "images/favicon.png"

  hideUntranslated = true

  generateSocialCard = true


 [params.author]
    name = "Ivan Béthus"
    email = "ivan.bethus@gmail.com" 