baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'

[languages]
[languages.en]
disabled = false
contentDir = 'content/en'
languageCode = 'en-US'
languageDirection = ""
languageName = "English"
weight = 2
[languages.fr]
disabled = false
contentDir = 'content/fr'
languageCode = 'fr-FR'
languageDirection = ""
languageName = "Français"
weight = 1
